[tox]
envlist =
    build_web


[testenv:build_web]
deps = 
    jupyterlite-core
    jupyterlite-pyodide-kernel
    nbstripout
allowlist_externals =
    rm
    nbstripout
commands = 
    - rm -rf docs
    nbstripout notebooks/*ipynb
    jupyter-lite build