[tox]
envlist =
    build_web


[testenv:build_web]
allowlist_externals =
    rm
    nbstripout
commands = 
    - rm -rf docs
    nbstripout notebooks/*ipynb
    jupyter-lite build


[testenv:bump_environment]
deps = 
    pip-tools
allowlist_externals =
commands = 
    pip-compile --upgrade pyproject.toml -o build-requirements.txt